---
title: "VDJ Detailed Visualizations"
author: "Niranjan Ilawe"
date: "10/25/2021"
output: html_document
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)

con <- DBI::dbConnect(RPostgres::Postgres(),
                      host = "cpdda.c7qfiffzqhfr.us-west-2.rds.amazonaws.com",
                      user = "cpdda",
                      password = ">TKd=lN7>jUiXTK.pSKV")

tbl_func <- dplyr::tbl(con, dbplyr::in_schema("gbmfg", "func_mfgdata"))

yield <- tbl_func %>%
  #filter(pn == "210170") %>%
  #filter(pn == "2000058") %>%
  select(pn, wo, unfunc_gb_vol_1, unfunc_gb_vol_2, lig1_vol, lig2_vol, final_vol) %>%
  mutate(unfunc_gb_vol_2 = if_else(is.na(unfunc_gb_vol_2), 0, unfunc_gb_vol_2)) %>%
  mutate(unfunc_gb_vol = (unfunc_gb_vol_1 + unfunc_gb_vol_2) / 4,
         yield = final_vol/unfunc_gb_vol*100) %>%
  select(wo, yield) %>%
  collect()

vols <- tbl_func %>%
  #filter(pn == "210170") %>%
  #filter(pn == "2000058") %>%
  select(pn, wo, mfg_date, unfunc_gb_vol_1, unfunc_gb_vol_2, lig1_vol, lig2_vol, final_vol) %>%
  mutate(unfunc_gb_vol_2 = if_else(is.na(unfunc_gb_vol_2), 0, unfunc_gb_vol_2)) %>%
  mutate(unfunc_gb_vol = (unfunc_gb_vol_1 + unfunc_gb_vol_2)/4) %>%
  select(-unfunc_gb_vol_1, -unfunc_gb_vol_2) %>%
  collect() %>%
  arrange(as.Date(mfg_date)) %>%
  group_by(pn, mfg_date) %>%
  mutate(overhang = 1:n()) %>%
  ungroup() %>%
  pivot_longer(cols = c(unfunc_gb_vol, lig1_vol, lig2_vol, final_vol), names_to = "step", values_to = "qty")
```

## Overall Yield


```{r overall, echo=FALSE, message=FALSE, warning=FALSE}
vols %>%
  left_join(yield, by = "wo") %>%
  filter(pn == "210170") %>%
  ggplot(.,aes(x = as.factor(wo), y = qty, fill = step)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_line(aes(y = yield*5), group=1) +
  geom_point(aes(y = yield*5), color = "black", size = 1) +
  geom_text(aes(y = yield*5, label = glue::glue("{round(yield,0)}%")), vjust = 2, size = 2, hjust = -0.5) +
  scale_y_continuous(
    # Features of the first axis
    name = "Volume of GBs (ml)",
    # Add a second axis and specify its features
    #sec.axis = sec_axis(~ scales::rescale(., to = range(chip_yield_tbl$max1)), name="Yield (%)")) +
    sec.axis = sec_axis(~./5, name="Yield % (Final Vol/Unfunc Vol)")) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(x = "Work Order")
  #facet_wrap(~overhang, scales = "free_x")
```


### Overhang wise Yield

```{r overhang, echo=FALSE, message=FALSE, warning=FALSE}
vols %>%
  left_join(yield, by = "wo") %>%
  filter(pn == "210170") %>%
  ggplot(.,aes(x = as.factor(wo), y = qty, fill = step)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_line(aes(y = yield*5), group=1) +
  geom_point(aes(y = yield*5), color = "black", size = 1) +
  geom_text(aes(y = yield*5, label = glue::glue("{round(yield,0)}%")), vjust = 2, size = 2, hjust = -0.5) +
  scale_y_continuous(
    # Features of the first axis
    name = "Volume of GBs (ml)",
    # Add a second axis and specify its features
    #sec.axis = sec_axis(~ scales::rescale(., to = range(chip_yield_tbl$max1)), name="Yield (%)")) +
    sec.axis = sec_axis(~./5, name="Yield % (Final Vol/Unfunc Vol)")) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(x = "Work Order") +
  facet_wrap(~overhang, scales = "free_x")
```

### Loss of Material Trend

```{r step, echo=FALSE, message=FALSE, warning=FALSE}
loss <- tbl_func %>%
  filter(pn == "210170") %>%
  #filter(pn == "2000058") %>%
  select(pn, wo, mfg_date, unfunc_gb_vol_1, unfunc_gb_vol_2, lig1_vol, lig2_vol, final_vol) %>%
  mutate(unfunc_gb_vol_2 = if_else(is.na(unfunc_gb_vol_2), 0, unfunc_gb_vol_2)) %>%
  mutate(unfunc_gb_vol = (unfunc_gb_vol_1 + unfunc_gb_vol_2) / 4,
         unfunc_to_lig1 = unfunc_gb_vol - lig1_vol,
         lig1_to_lig2 = lig1_vol - lig2_vol,
         lig2_to_final = lig2_vol - final_vol) %>% 
  select(-unfunc_gb_vol_1, -unfunc_gb_vol_2, -unfunc_gb_vol, -lig1_vol, -lig2_vol, -final_vol) %>%
  collect() %>%
  arrange(as.Date(mfg_date)) %>%
  group_by(pn, mfg_date) %>%
  mutate(overhang = 1:n()) %>%
  ungroup() %>%
  pivot_longer(cols = c(unfunc_to_lig1, lig1_to_lig2, lig2_to_final), names_to = "step", values_to = "qty")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
loss %>% 
  ggplot(., aes(x = as.factor(wo), y = -qty, color = step)) +
  geom_line(aes(group = step)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(x = "Work Order", y = "mL Lost")
```

#### Loss of Material per Overhang Trend

```{r echo=FALSE, message=FALSE, warning=FALSE}
loss %>% 
  ggplot(., aes(x = as.factor(wo), y = -qty, color = step)) +
  geom_line(aes(group = step)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(x = "Work Order", y = "mL Lost") +
  facet_wrap(~overhang, scales = "free")
```