---
title: "VDJ_GB Process Data"
author: "Niranjan Ilawe"
date: "11/2/2021"
output: html_document
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)

con <- DBI::dbConnect(RPostgres::Postgres(),
                      host = "cpdda.c7qfiffzqhfr.us-west-2.rds.amazonaws.com",
                      user = "cpdda",
                      password = ">TKd=lN7>jUiXTK.pSKV")

tbl_func <- dplyr::tbl(con, dbplyr::in_schema("gbmfg", "func_mfgdata")) %>% 
  filter(pn == '210170') %>% 
  collect() %>% 
  group_by(ln) %>% 
  mutate(func_vol = sum(final_vol)) %>% 
  ungroup() %>% 
  distinct(pn, ln, mfg_date, unfunc_gb_vol_1, total_lig1_vol, total_lig2_vol, func_vol)

tbl_disp <- dplyr::tbl(con, dbplyr::in_schema("gbmfg", "disp_mfgdata")) %>% 
  filter(pn == "2000209") %>% 
  collect() %>% 
  mutate(ln = str_extract(ln, "^\\d+")) %>% 
  select(gb_vol_for_dispense, ln, mfg_qty, scrap_qty, qc_retain_qty)

df <- left_join(tbl_func, tbl_disp, by = c("ln")) %>% 
  drop_na()

yield <- df %>%
  select(ln, unfunc_gb_vol_1, gb_vol_for_dispense) %>%
  mutate(yield = gb_vol_for_dispense/unfunc_gb_vol_1*100) %>%
  select(ln, yield)

vols <- df %>% 
  select(pn, ln, mfg_date, unfunc_gb_vol_1, total_lig1_vol, total_lig2_vol, func_vol, gb_vol_for_dispense, mfg_qty, scrap_qty, qc_retain_qty) %>%
  arrange(as.Date(mfg_date)) %>%
  pivot_longer(cols = c(unfunc_gb_vol_1, total_lig1_vol, total_lig2_vol, func_vol, gb_vol_for_dispense, mfg_qty, scrap_qty, qc_retain_qty), names_to = "step", values_to = "qty")
```

## Overall Yield


```{r overall, echo=FALSE, message=FALSE, warning=FALSE}
vols %>%
  left_join(yield, by = "ln") %>%
  ggplot(.,aes(x = as.factor(ln), y = qty, fill = step)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_line(aes(y = yield*15), group=1) +
  geom_point(aes(y = yield*15), color = "black", size = 1) +
  geom_text(aes(y = yield*15, label = glue::glue("{round(yield,0)}%")), vjust = 2, size = 2, hjust = -0.5) +
  scale_y_continuous(
    # Features of the first axis
    name = "Volume of GBs (ml)",
    # Add a second axis and specify its features
    #sec.axis = sec_axis(~ scales::rescale(., to = range(chip_yield_tbl$max1)), name="Yield (%)")) +
    sec.axis = sec_axis(~./15, name="Yield % (Final Vol/Unfunc Vol)")) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(x = "Work Order")
  #facet_wrap(~overhang, scales = "free_x")
```

### Loss of Material Trend

```{r step, echo=FALSE, message=FALSE, warning=FALSE}
loss <- df %>%
  select(pn, ln, mfg_date, unfunc_gb_vol_1, total_lig1_vol, total_lig2_vol, func_vol, gb_vol_for_dispense) %>%
  mutate(unfunc_to_lig1 = unfunc_gb_vol_1 - total_lig1_vol,
         lig1_to_lig2 = total_lig1_vol - total_lig2_vol,
         lig2_to_func = total_lig2_vol - func_vol,
         func_to_wash = func_vol - gb_vol_for_dispense) %>% 
  select(-unfunc_gb_vol_1, -total_lig1_vol, -total_lig2_vol, -func_vol, -gb_vol_for_dispense) %>%
  collect() %>%
  arrange(as.Date(mfg_date)) %>%
  pivot_longer(cols = c(unfunc_to_lig1, lig1_to_lig2, lig2_to_func, func_to_wash), names_to = "step", values_to = "qty")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
loss %>% 
  ggplot(., aes(x = as.factor(ln), y = -qty, color = step)) +
  geom_line(aes(group = step, linetype = step), size = 1) +
  geom_point() +
  geom_hline(yintercept = 0) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(x = "Work Order", y = "mL Lost") 
```

## Material Loss Trend


```{r echo=FALSE, message=FALSE, warning=FALSE}
vols_sub <- vols %>% 
  filter(step %in% c("unfunc_gb_vol_1", "total_lig1_vol", "total_lig2_vol", "func_vol", "gb_vol_for_dispense"))

vols_sub$step <- factor(vols_sub$step, levels = c("unfunc_gb_vol_1", "total_lig1_vol", "total_lig2_vol", "func_vol", "gb_vol_for_dispense"))

vols_sub %>% 
  ggplot(.,aes(x = step, y = qty, color = ln)) +
  geom_line(aes(group = ln))
```

## Divvar Trends

```{r echo=FALSE, message=FALSE, warning=FALSE}
tbl_divvar <- dplyr::tbl(con, dbplyr::in_schema("gbmfg", "func_divvar_data")) %>% 
  filter(pn %in% c('210170','210170/2000461'),
         ln != "69-A") %>% 
  collect()

tbl_divvar %>% 
  ggplot(., aes(x = reorder(ln, date), y = data_value, color = data_name)) +
  geom_point() +
  facet_wrap(~data_name, nrow = 3, scales = "free_y") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  theme(legend.position = "none")
```

### HSV


```{r echo=FALSE, message=FALSE, warning=FALSE}
tbl_hsv <- dplyr::tbl(con, dbplyr::in_schema("gbmfg", "func_hsv_data")) %>% 
  filter(pn == '2000209') %>% 
  collect()

tbl_hsv %>% 
  ggplot(., aes(x = reorder(wo, as.Date(qc_date)), y = ggf, color = bead_lot)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) 
```

### BIF


```{r echo=FALSE, message=FALSE, warning=FALSE}
tbl_hsv %>% 
  ggplot(., aes(x = reorder(wo, as.Date(qc_date)), y = bif, color = bead_lot)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) 
```

## Flowcam


```{r echo=FALSE, message=FALSE, warning=FALSE}
tbl_hsv <- dplyr::tbl(con, dbplyr::in_schema("gbmfg", "func_flowcam_data")) %>% 
  filter(pn == '210170') %>% 
  collect()

tbl_hsv %>% 
  ggplot(., aes(x = reorder(ln, date), y = data_value, color = data_name)) +
  geom_point() +
  facet_wrap(~data_name, nrow = 3, scales = "free_y") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  theme(legend.position = "None")
```

