-- HSV DATA TABLE
drop table if exists gbmfg.disp_hsv_data;
create table gbmfg.disp_hsv_data (
	qc_date varchar(30) null,
	pn varchar(30),
	wo varchar(30),
	qc_operator varchar(30) null,
	run_name varchar(100) null,
	chip_used varchar(50) null,
	layout varchar(20) null,
	chip_lot varchar(20) null,
	oil_lot varchar(20) null,
	bead_lot varchar(20) null,
	hsv varchar(20) null,
	eeprom varchar(20) null,
	is_pinned_gem boolean null,
	is_clog_debris boolean null,
	is_wetting_failure boolean null,
	start_time varchar(30) null,
	end_time varchar(30) null,
	n_equal_0 numeric(12,4) null,
	n_equal_1 numeric(12,4) null,
	n_greater_1 numeric(12,4) null,
	ggf numeric(12,4) null,
	ggf_cv numeric(12,4) null,
	bif numeric(12,4) null,
	bif_cv numeric(12,4) null,
	cg_rate numeric(12,4) null,
	tether_rate numeric(12,4) null,
	drift numeric(12,4) null,
	big_clump_count numeric(12,4) null,
	bif_true_cv numeric(12,4) null,
	small_clump_count numeric(12,4) null,
	local_noise_cv numeric(12,4) null
);